/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#009668",
        "on-secondary-fixed": "#00174b",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7c839b",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#fefcff",
        "tertiary-container": "#002113",
        "tertiary-fixed": "#6ffbbe",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#131b2e",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#4edea3",
        "on-error-container": "#93000a",
        "surface-tint": "#565e74",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#002113",
        "secondary": "#0051d5",
        "background": "#f7f9fb",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "on-primary-fixed": "#131b2e",
        "surface-dim": "#d8dadc",
        "tertiary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-high": "#e6e8ea",
        "secondary-container": "#316bf3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "stack-lg": "32px",
        "sidebar-expanded": "280px",
        "header-height": "72px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "margin-desktop": "32px",
        "sidebar-collapsed": "80px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "button": ["14px", { "lineHeight": "1", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in',
        'slide-in': 'slideIn 0.3s ease-out',
        'fade-in-scale': 'fadeInScale 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeInScale: {
          '0%': { opacity: '0', transform: 'scale(0.95) translateY(20px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        }
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
